Python使用被称为异常 的特殊对象来管理程序执行期间发生的错误。

- 异常是使用 `try-except` 代码块处理的。
- 发生错误时，如果程序还有工作没有完成，妥善地处理错误就尤其重要。